# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    mkdir -p $(Build.ArtifactStagingDirectory)/test
    echo Add other tasks to build, test, and deploy your project. > $(Build.ArtifactStagingDirectory)/test/test0.txt
    echo See https://aka.ms/yaml > $(Build.ArtifactStagingDirectory)/test/test1.txt
    ls $(Build.ArtifactStagingDirectory)/test/test1.txt
  displayName: 'Run a multi-line script'

- task: GithubRelease@0
  displayName: Create GitHub Release
  inputs:
   githubConnection: Azure Test Release
